//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoPlace
{
    using System;
    using System.Collections.Generic;
    
    public partial class Report
    {
        public int IdReport { get; set; }
        public int IdCard { get; set; }
        public int IdWorker { get; set; }
        public System.DateTime CheckInTime { get; set; }
        public System.DateTime CheckOutTime { get; set; }
    
        public virtual Card Card { get; set; }
        public virtual Worker Worker { get; set; }
    }
}
